/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class corelyzer_plugin_correlator_Correlator */

#ifndef _Included_corelyzer_plugin_correlator_Correlator
#define _Included_corelyzer_plugin_correlator_Correlator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     corelyzer_plugin_correlator_Correlator
 * Method:    init
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_corelyzer_plugin_correlator_Correlator_init
  (JNIEnv *, jclass);

/*
 * Class:     corelyzer_plugin_correlator_Correlator
 * Method:    finish
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_corelyzer_plugin_correlator_Correlator_finish
  (JNIEnv *, jclass);

/*
 * Class:     corelyzer_plugin_correlator_Correlator
 * Method:    updateData
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_corelyzer_plugin_correlator_Correlator_updateData
  (JNIEnv *, jclass);

/*
 * Class:     corelyzer_plugin_correlator_Correlator
 * Method:    execute
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_corelyzer_plugin_correlator_Correlator_execute
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     corelyzer_plugin_correlator_Correlator
 * Method:    setCoreFormat
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_corelyzer_plugin_correlator_Correlator_setCoreFormat
  (JNIEnv *, jclass, jint);

/*
 * Class:     corelyzer_plugin_correlator_Correlator
 * Method:    getCoreFormat
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_corelyzer_plugin_correlator_Correlator_getCoreFormat
  (JNIEnv *, jclass);

/*
 * Class:     corelyzer_plugin_correlator_Correlator
 * Method:    setCoreType
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_corelyzer_plugin_correlator_Correlator_setCoreType
  (JNIEnv *, jclass, jint);

/*
 * Class:     corelyzer_plugin_correlator_Correlator
 * Method:    getCoreType
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_corelyzer_plugin_correlator_Correlator_getCoreType__
  (JNIEnv *, jclass);

/*
 * Class:     corelyzer_plugin_correlator_Correlator
 * Method:    loadAffineTable
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_corelyzer_plugin_correlator_Correlator_loadAffineTable
  (JNIEnv *, jclass, jstring);

/*
 * Class:     corelyzer_plugin_correlator_Correlator
 * Method:    loadSpliceTable
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_corelyzer_plugin_correlator_Correlator_loadSpliceTable
  (JNIEnv *, jclass, jstring);

/*
 * Class:     corelyzer_plugin_correlator_Correlator
 * Method:    loadData
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_corelyzer_plugin_correlator_Correlator_loadData
  (JNIEnv *, jclass, jstring);

/*
 * Class:     corelyzer_plugin_correlator_Correlator
 * Method:    getHoleNames
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_corelyzer_plugin_correlator_Correlator_getHoleNames
  (JNIEnv *, jclass);

/*
 * Class:     corelyzer_plugin_correlator_Correlator
 * Method:    getCoreNames
 * Signature: (I)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_corelyzer_plugin_correlator_Correlator_getCoreNames
  (JNIEnv *, jclass, jint);

/*
 * Class:     corelyzer_plugin_correlator_Correlator
 * Method:    getSectionNames
 * Signature: (II)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_corelyzer_plugin_correlator_Correlator_getSectionNames
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     corelyzer_plugin_correlator_Correlator
 * Method:    getLeg
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_corelyzer_plugin_correlator_Correlator_getLeg
  (JNIEnv *, jclass, jint);

/*
 * Class:     corelyzer_plugin_correlator_Correlator
 * Method:    getSite
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_corelyzer_plugin_correlator_Correlator_getSite
  (JNIEnv *, jclass, jint);

/*
 * Class:     corelyzer_plugin_correlator_Correlator
 * Method:    getCoreType
 * Signature: (II)C
 */
JNIEXPORT jchar JNICALL Java_corelyzer_plugin_correlator_Correlator_getCoreType__II
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     corelyzer_plugin_correlator_Correlator
 * Method:    getHoleData
 * Signature: (I)[F
 */
JNIEXPORT jfloatArray JNICALL Java_corelyzer_plugin_correlator_Correlator_getHoleData
  (JNIEnv *, jclass, jint);

/*
 * Class:     corelyzer_plugin_correlator_Correlator
 * Method:    getDataTuple
 * Signature: (III)[F
 */
JNIEXPORT jfloatArray JNICALL Java_corelyzer_plugin_correlator_Correlator_getDataTuple
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     corelyzer_plugin_correlator_Correlator
 * Method:    debugPrintOut
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_corelyzer_plugin_correlator_Correlator_debugPrintOut
  (JNIEnv *, jclass);

/*
 * Class:     corelyzer_plugin_correlator_Correlator
 * Method:    printoutData
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_corelyzer_plugin_correlator_Correlator_printoutData
  (JNIEnv *, jclass);

/*
 * Class:     corelyzer_plugin_correlator_Correlator
 * Method:    setCullFilter
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_corelyzer_plugin_correlator_Correlator_setCullFilter
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     corelyzer_plugin_correlator_Correlator
 * Method:    setCullTop
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_corelyzer_plugin_correlator_Correlator_setCullTop
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     corelyzer_plugin_correlator_Correlator
 * Method:    setCullNo
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_corelyzer_plugin_correlator_Correlator_setCullNo
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     corelyzer_plugin_correlator_Correlator
 * Method:    setCullSignal
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_corelyzer_plugin_correlator_Correlator_setCullSignal
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     corelyzer_plugin_correlator_Correlator
 * Method:    setCullEquation
 * Signature: (FFIII)V
 */
JNIEXPORT void JNICALL Java_corelyzer_plugin_correlator_Correlator_setCullEquation
  (JNIEnv *, jclass, jfloat, jfloat, jint, jint, jint);

/*
 * Class:     corelyzer_plugin_correlator_Correlator
 * Method:    setDecimationFilter
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_corelyzer_plugin_correlator_Correlator_setDecimationFilter
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     corelyzer_plugin_correlator_Correlator
 * Method:    setDecimationParam
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_corelyzer_plugin_correlator_Correlator_setDecimationParam
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     corelyzer_plugin_correlator_Correlator
 * Method:    setGaussianFilter
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_corelyzer_plugin_correlator_Correlator_setGaussianFilter
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     corelyzer_plugin_correlator_Correlator
 * Method:    setGaussianParam
 * Signature: (FI)V
 */
JNIEXPORT void JNICALL Java_corelyzer_plugin_correlator_Correlator_setGaussianParam
  (JNIEnv *, jclass, jfloat, jint);

/*
 * Class:     corelyzer_plugin_correlator_Correlator
 * Method:    getTuple
 * Signature: (I)[F
 */
JNIEXPORT jfloatArray JNICALL Java_corelyzer_plugin_correlator_Correlator_getTuple
  (JNIEnv *, jclass, jint);

/*
 * Class:     corelyzer_plugin_correlator_Correlator
 * Method:    getSectionInterval
 * Signature: (III)[F
 */
JNIEXPORT jfloatArray JNICALL Java_corelyzer_plugin_correlator_Correlator_getSectionInterval
  (JNIEnv *, jclass, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
