package corelyzer.ui;

import java.awt.Frame;
import java.awt.Insets;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.Vector;

import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComponent;
import javax.swing.JDialog;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.KeyStroke;
import javax.swing.ListModel;
import javax.swing.event.ListDataListener;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;

class CheckBoxListModel implements ListModel {
	Vector<JCheckBox> sessions;

	public CheckBoxListModel(final ListModel m) {
		if (m == null) {
			return;
		}

		sessions = new Vector<JCheckBox>();

		for (int i = 0; i < m.getSize(); i++) {
			String sessionName = m.getElementAt(i).toString();
			sessions.add(new JCheckBox(sessionName, true));
		}
	}

	public void addListDataListener(final ListDataListener listDataListener) {
		// do nothing
	}

	public Object getElementAt(final int i) {
		if (sessions == null) {
			return null;
		} else {
			return sessions.elementAt(i);
		}
	}

	public int getSize() {
		if (sessions == null) {
			return 0;
		} else {
			return sessions.size();
		}
	}

	public void removeListDataListener(final ListDataListener listDataListener) {
		// do nothing
	}
}

public class SessionsSelectDialog extends JDialog {
	/**
	 * 
	 */
	private static final long serialVersionUID = -5845300587940135499L;

	public static void main(final String[] args) {
		SessionsSelectDialog dialog = new SessionsSelectDialog(null);
		dialog.pack();
		dialog.setVisible(true);
		System.exit(0);
	}

	private JPanel contentPane;
	private JButton buttonOK;
	private JButton buttonCancel;
	private JScrollPane checkListScrollPane;

	private JList sessList;

	private boolean isCancelled = false;

	public SessionsSelectDialog(final Frame parent) {
		super(parent, "Check sessions to save");

		$$$setupUI$$$();
		setContentPane(contentPane);
		setModal(true);
		getRootPane().setDefaultButton(buttonOK);

		buttonOK.addActionListener(new ActionListener() {

			public void actionPerformed(final ActionEvent e) {
				onOK();
			}
		});

		buttonCancel.addActionListener(new ActionListener() {

			public void actionPerformed(final ActionEvent e) {
				onCancel();
			}
		});

		setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
		addWindowListener(new WindowAdapter() {

			@Override
			public void windowClosing(final WindowEvent e) {
				onCancel();
			}
		});

		contentPane.registerKeyboardAction(new ActionListener() {

			public void actionPerformed(final ActionEvent e) {
				onCancel();
			}
		}, KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
	}

	/**
	 * @noinspection ALL
	 */
	public JComponent $$$getRootComponent$$$() {
		return contentPane;
	}

	/**
	 * Method generated by IntelliJ IDEA GUI Designer >>> IMPORTANT!! <<< DO NOT
	 * edit this method OR call it in your code!
	 * 
	 * @noinspection ALL
	 */
	private void $$$setupUI$$$() {
		createUIComponents();
		contentPane = new JPanel();
		contentPane.setLayout(new GridLayoutManager(2, 1, new Insets(10, 10, 10, 10), -1, -1));
		final JPanel panel1 = new JPanel();
		panel1.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
		contentPane.add(panel1, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK
				| GridConstraints.SIZEPOLICY_CAN_GROW, 1, null, null, null, 0, false));
		final Spacer spacer1 = new Spacer();
		panel1.add(spacer1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL,
				GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
		final JPanel panel2 = new JPanel();
		panel2.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1, true, false));
		panel1.add(panel2, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK
				| GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
		buttonOK = new JButton();
		buttonOK.setText("OK");
		panel2.add(buttonOK, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL,
				GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
		buttonCancel = new JButton();
		buttonCancel.setText("Cancel");
		panel2.add(buttonCancel, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL,
				GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
		final JPanel panel3 = new JPanel();
		panel3.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
		contentPane
				.add(panel3, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK
						| GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null,
						0, false));
		checkListScrollPane = new JScrollPane();
		panel3.add(checkListScrollPane, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH,
				GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK
						| GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
		checkListScrollPane.setViewportView(sessList);
	}

	private void createUIComponents() {
		CorelyzerApp app = CorelyzerApp.getApp();

		if (app == null) {
			return;
		}

		sessList = new CheckBoxList();
		sessList.setModel(new CheckBoxListModel(app.getSessionListModel()));
	}

	public boolean[] getSelectedIndex() {
		if (this.isCancelled) {
			return null;
		}

		boolean hasSelection = false;
		if (sessList != null) {
			CheckBoxList l = (CheckBoxList) sessList;
			boolean[] ret = new boolean[l.getModel().getSize()];

			for (int i = 0; i < ret.length; i++) {
				JCheckBox cb = (JCheckBox) l.getModel().getElementAt(i);
				ret[i] = cb.isSelected();
				if (ret[i])
					hasSelection = true;
			}

			if (hasSelection)
				return ret;
		}
		return null;
	}
	
	// returns text of first selected checkbox
	public String getSelectedIndexName() {
		String result = null;
		if ( !this.isCancelled && sessList != null )
		{
			CheckBoxList l = (CheckBoxList) sessList;

			for (int i = 0; i < l.getModel().getSize(); i++) {
				JCheckBox cb = (JCheckBox) l.getModel().getElementAt(i);
				if ( cb.isSelected() )
				{
					result = cb.getText();
					break;
				}
			}
		}	

		return result;
	}

	private void onCancel() {
		this.isCancelled = true;
		dispose();
	}

	private void onOK() {
		this.isCancelled = false;
		dispose();
	}
}